name: Gathering Pipeline Statistics
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  Gather_Statistics:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    env:
      ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Artifacts Directory
        run: mkdir -p ${{ env.ARTIFACTS_DIR }}

      - name: Show Context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.runId)
            console.log(context.payload.repository.full_name)

#            let workflowJobs = await github.rest.actions.listJobsForWorkflowRun({
#              'owner': context.payload.repository.organization,
#              'repo': context.payload.repository.name,
#              'run_id': context.runId
#            })
#            console.log(JSON.stringify(workflowJobs))
            
#            let timeSpent = await github.rest.actions.getWorkflowRunUsage({
#              'owner': context.payload.repository.organization,
#              'repo': context.payload.repository.name,
#              'run_id': context.runId
#            })
#            console.log(JSON.stringify(timeSpent))
      - name: List All Workflow Runs
        uses: actions/github-script@v6
        with:
          script: |
            
            let date = new Date();
            
            var day = date.getDate();
            // Month is starting from 0 for some reason
            var month = date.getMonth() + 1;
            let year = date.getFullYear();
            
            if (day < 10) {
              day = `0${day}`
            }
            
            if (month < 10) {
              month = `0${month}`
            }
            
            // Only gather workflow runs that ran on the specified date or after
            // let dateToStartGatheringFrom = `>=${year}-${month}-${day}`
            
            let dateToStartGatheringFrom = `>=2023-07-05`
            console.log(`dateToStartGatheringFrom: ${dateToStartGatheringFrom}`)
            
            // TODO: use context.payload.repository.organization
            let org = 'openvinotoolkit'
            
            // TODO: use context.payload.repository.name
            let repositoryName = 'openvino_contrib'
            
            let workflowRuns = await github.rest.actions.listWorkflowRuns({
              'owner': org,
              'repo': repositoryName,
              'workflow_id': 'test_linux.yml',
              'status': 'completed',
              'created': dateToStartGatheringFrom
            })
            // console.log(JSON.stringify(workflowRuns))
            
            let artifactPath = `${{ env.ARTIFACTS_DIR }}/workflowRuns.json`
            
            var fs = require('fs');
            fs.writeFile(artifactPath, JSON.stringify(workflowRuns), function(err) {
                if (err) {
                    console.log(err);
                }
            });

      - name: Upload gathered data
        uses: actions/upload-artifact@v3
        with:
          name: workflowRuns
          path: ${{ env.ARTIFACTS_DIR }}/workflowRuns.json
          if-no-files-found: 'error'
