name: Tests on Linux
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Sample Stage
        run: |
          echo "123"

      - name: Get GitHub Context Values
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.repositoryUrl }}
          
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: Set Var if Merged
        if: github.event.pull_request.merged == true
        run: |
          echo "SOME_VAR=true" >> $GITHUB_ENV

      - name: Check Var
        if: github.event.pull_request.merged == true
        run: |
          echo ${{ env.SOME_VAR }}

      - name: Clone
        run: |
          git clone ${{ github.event.pull_request.head.repo.clone_url }} ${{ env.BASE_REPO_DIR }} && cd ${{ env.BASE_REPO_DIR }} && git checkout ${{ github.head_ref }} && cat README.md
        env:
          BASE_REPO_DIR: baseRepo