name: Tests on Linux
on:
  pull_request_target:
    types: [ labeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Sample Stage
        run: |
          echo "123"

      - name: Verify Secrets
        run: |
          echo ${{ secrets.SAMPLE_SECRET }}
          echo ${{ secrets.NON_EXISTENT }}

      - name: Get tools versions
        run: python3 --version || exit 1

      - name: Get GitHub Context Values
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.repositoryUrl }}
          
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: Clone
        run: |
          git clone ${{ github.event.pull_request.head.repo.clone_url }} ${{ env.BASE_REPO_DIR }} && cd ${{ env.BASE_REPO_DIR }} && git checkout ${{ github.head_ref }} && cat README.md
        env:
          BASE_REPO_DIR: baseRepo